### ISSUE TITLE
Directory should be created using "react-native init".

### ISSUE THREAD

**Issue by quincyhut** [junedomingo/react-native-rename#166]
Hi,
I get this when i run the command npx react-native-rename "name"

this worked fine on 2.9.0 a week back. I created the project with npx react-native init "name" back then

update: reverting to 2.9.0 worked for me

**Comment by junedomingo** [comment]
Hi @quincyhut , what version of rnr are you using?

**Comment by junedomingo** [comment]
do you have `android/app/src/main/res/values/strings.xml` and `ios/*/Info.plist` files?

**Comment by quincyhut** [comment]
Hi @junedomingo 
i noticed 3.1.3 was out and used that 
yes, i  have the files android\app\src\main\res\values\strings.xml and ios/appname/Info.plist

**Comment by shehanhasanga** [comment]
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module 'node:process'
Require stack:
- E:\bitbucket\medhub\chnageappname\mobileapp\node_modules\react-native-rename\lib\index.js

**Comment by PauloMello99** [comment]
@quincyhut Try running the command from a terminal outside VS Code, I was able to do it using Windows PowerShell

**Comment by junedomingo** [comment]
I just published v3.2.2 with Windows support, let me know how it goes @quincyhut @PauloMello99

**Comment by hannanstd** [comment]
Hello. Thank you.
Does it support the macos one?
https://microsoft.github.io/react-native-windows/docs/rnm-getting-started
